local awful = require("awful")

require("module.notifications")
require("module.notification-center")
require("module.bluetooth-center")
require("module.network-center")
require("module.volume-center")
require("module.double-border")
require("module.calendar")
require("module.settings")
local exit_screen = require("module.exit-screen")
local control_center = require("module.control-center")
local bar = require("module.bar")
awful.screen.connect_for_each_screen(exit_screen)
awful.screen.connect_for_each_screen(control_center)
awful.screen.connect_for_each_screen(bar)
